/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.dangKyTheThangController;
import controller.dangKyTheVipController;
import controller.khuController;
import controller.quyDinhController;
import controller.viTriController;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import model.khu;
import model.taiKhoan;
import model.viTri;

/**
 *
 * @author Admin
 */
public class dangKyTheVip extends javax.swing.JPanel {

    private Date date;
    public taiKhoan tk;
    String ngayThangNam;

    /**
     * Creates new form dangKyTheThang
     */
    public dangKyTheVip(taiKhoan tk) {

        initComponents();
        this.tk = tk;
        date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        ngayThangNam = formatter.format(date);
        txtNgayDangKy.setText(ngayThangNam);
        date.setYear(date.getYear() + 1);
        txtNgayHetHan.setText(formatter.format(date));
        txtTenNhanVien.setText(tk.getTenDangNhap());
        txtTien.setText(String.valueOf(quyDinhController.layGiaTien("20")));
        cbb.setSelectedIndex(0);
        ArrayList<khu> list = khuController.layDanhSachKhuVip((String) cbb.getSelectedItem());
        cbbKhu.removeAllItems();
        for (int i = 0; i < list.size(); i++) {
            cbbKhu.insertItemAt(list.get(i).getMaKhu(), i);
        }
        cbbKhu.setSelectedItem(list.get(0).getMaKhu());
        ArrayList<viTri> list1 = viTriController.layDanhSachViTri((String) cbbKhu.getSelectedItem());
        cbbViTri.removeAllItems();
        for (int i = 0; i < list1.size(); i++) {
            cbbViTri.insertItemAt(list1.get(i).getMaViTri(), i);
        }
        cbbViTri.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sss = new javax.swing.JLabel();
        ss = new javax.swing.JLabel();
        sdf = new javax.swing.JLabel();
        sdfsdf = new javax.swing.JLabel();
        ssdfg = new javax.swing.JLabel();
        dsfgs = new javax.swing.JLabel();
        sdfgg = new javax.swing.JLabel();
        gsdfff = new javax.swing.JLabel();
        txtMaThe = new javax.swing.JTextField();
        txtBienSoXe = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtNgayDangKy = new javax.swing.JTextField();
        txtTien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbbKhu = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbbViTri = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbbThoiHan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtNgayHetHan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(950, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Đăng ký thẻ VIP");

        sss.setText("Mã thẻ");

        ss.setText("Loại xe");

        sdf.setText("Biển số xe");

        sdfsdf.setText("Tên khách hàng");

        ssdfg.setText("CCCD");

        dsfgs.setText("Số điện thoại");

        sdfgg.setText("Ngày đăng ký");

        gsdfff.setText("Giá tiền");

        txtMaThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTheActionPerformed(evt);
            }
        });

        txtSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiActionPerformed(evt);
            }
        });

        cbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O to", "Xe may" }));
        cbb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbItemStateChanged(evt);
            }
        });
        cbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbActionPerformed(evt);
            }
        });

        jLabel3.setText("Nhân viên lập");

        jLabel4.setText("Khu");

        cbbKhu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Vị trí");

        cbbViTri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Thời hạn");

        cbbThoiHan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 tháng", "3 tháng", "6 tháng", "1 năm", "3 năm", "5 năm", "10 năm" }));
        cbbThoiHan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbThoiHanItemStateChanged(evt);
            }
        });
        cbbThoiHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThoiHanActionPerformed(evt);
            }
        });

        jLabel7.setText("Ngày hết hạn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ss)
                    .addComponent(sdf)
                    .addComponent(sss)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaThe)
                    .addComponent(cbb, 0, 100, Short.MAX_VALUE)
                    .addComponent(txtBienSoXe)
                    .addComponent(cbbKhu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ssdfg)
                    .addComponent(dsfgs)
                    .addComponent(sdfsdf)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenKhachHang)
                    .addComponent(txtCCCD)
                    .addComponent(txtSoDienThoai)
                    .addComponent(cbbViTri, 0, 100, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sdfgg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayDangKy)
                            .addComponent(cbbThoiHan, 0, 100, Short.MAX_VALUE)
                            .addComponent(txtNgayHetHan))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gsdfff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sss)
                            .addComponent(sdfsdf)
                            .addComponent(txtMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sdfgg)
                            .addComponent(txtNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gsdfff))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ss)
                                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ssdfg))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(cbbThoiHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTien, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdf)
                    .addComponent(dsfgs)
                    .addComponent(txtBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtNgayHetHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbbKhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(cbbViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jButton1.setText("Lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTheActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtMaThe.getText().equals("") || txtBienSoXe.getText().equals("") || txtTenKhachHang.getText().equals("") || txtCCCD.getText().equals("") || txtSoDienThoai.getText().equals("") || txtTien.getText().equals("")) {
            JOptionPane.showMessageDialog(jButton1, "Hãy nhập đầy đủ thông tin");
        } else {
            String maLoaiThe = "8";
            if (cbb.getSelectedIndex() == 0) {
                maLoaiThe = "8";
            }
            if (cbb.getSelectedIndex() == 1) {
                maLoaiThe = "7";
            }
            if (dangKyTheVipController.taoTheVip(txtMaThe.getText(), maLoaiThe, txtBienSoXe.getText(), cbbKhu.getSelectedItem().toString(), cbbViTri.getSelectedItem().toString(), txtTenKhachHang.getText(), txtCCCD.getText(), txtSoDienThoai.getText(), txtNgayDangKy.getText(), txtNgayHetHan.getText(), Integer.valueOf(txtTien.getText()), txtTenNhanVien.getText())) {
                JOptionPane.showMessageDialog(jButton1, "Tạo thẻ Vip mới thành công");
                txtMaThe.setText("");
                txtBienSoXe.setText("");
                txtTenKhachHang.setText("");
                txtCCCD.setText("");
                txtSoDienThoai.setText("");
                viTriController.coXe(cbbViTri.getSelectedItem().toString());
                khuController.nhanXe(cbbKhu.getSelectedItem().toString());
            } else {
                JOptionPane.showMessageDialog(jButton1, "Mã thẻ đã tồn tại");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbItemStateChanged
        // TODO add your handling code here:
        cbbThoiHan.setSelectedIndex(0);
        String maQuyDinh = null;
        if (cbb.getSelectedIndex() == 0) {
            maQuyDinh = "13";
        }
        if (cbb.getSelectedIndex() == 1) {
            maQuyDinh = "23";
        }
        txtTien.setText(String.valueOf(quyDinhController.layGiaTien(maQuyDinh)));
        ArrayList<khu> list = khuController.layDanhSachKhuVip((String) cbb.getSelectedItem());
        cbbKhu.removeAllItems();
        for (int i = 0; i < list.size(); i++) {
            cbbKhu.insertItemAt(list.get(i).getMaKhu(), i);
        }
        cbbKhu.setSelectedItem(list.get(0).getMaKhu());
        cbbKhu.setSelectedItem(list.get(0).getMaKhu());
        ArrayList<viTri> list1 = viTriController.layDanhSachViTri((String) cbbKhu.getSelectedItem());
        cbbViTri.removeAllItems();
        for (int i = 0; i < list1.size(); i++) {
            cbbViTri.insertItemAt(list1.get(i).getMaViTri(), i);
        }
        cbbViTri.setSelectedIndex(0);
    }//GEN-LAST:event_cbbItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtMaThe.setText("");
        txtBienSoXe.setText("");
        txtTenKhachHang.setText("");
        txtCCCD.setText("");
        txtSoDienThoai.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiActionPerformed

    private void cbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbActionPerformed

    private void cbbThoiHanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbThoiHanItemStateChanged
        // TODO add your handling code here:
        date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        if (cbbThoiHan.getSelectedIndex() == 0) {
            date.setMonth(date.getMonth() + 1);
            txtNgayHetHan.setText(formatter.format(date));
        }
        if (cbbThoiHan.getSelectedIndex() == 1) {
            date.setMonth(date.getMonth() + 3);
            txtNgayHetHan.setText(formatter.format(date));
        }
        if (cbbThoiHan.getSelectedIndex() == 2) {
            date.setMonth(date.getMonth() + 6);
            txtNgayHetHan.setText(formatter.format(date));
        }
        if (cbbThoiHan.getSelectedIndex() == 3) {
            date.setYear(date.getYear() + 1);
            txtNgayHetHan.setText(formatter.format(date));
        }
        if (cbbThoiHan.getSelectedIndex() == 4) {
            date.setYear(date.getYear() + 3);
            txtNgayHetHan.setText(formatter.format(date));
        }
        if (cbbThoiHan.getSelectedIndex() == 5) {
            date.setYear(date.getYear() + 5);
            txtNgayHetHan.setText(formatter.format(date));
        }
        if (cbbThoiHan.getSelectedIndex() == 6) {
            date.setYear(date.getYear() + 10);
            txtNgayHetHan.setText(formatter.format(date));
        }
        if (cbb.getSelectedIndex() == 0) {
            if (cbbThoiHan.getSelectedIndex() == 0) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("20")));
            }
            if (cbbThoiHan.getSelectedIndex() == 1) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("21")));
            }
            if (cbbThoiHan.getSelectedIndex() == 2) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("22")));
            }
            if (cbbThoiHan.getSelectedIndex() == 3) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("13")));
            }
            if (cbbThoiHan.getSelectedIndex() == 4) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("14")));
            }
            if (cbbThoiHan.getSelectedIndex() == 5) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("15")));
            }
            if (cbbThoiHan.getSelectedIndex() == 6) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("16")));
            }
        }
        if (cbb.getSelectedIndex() == 1) {
            if (cbbThoiHan.getSelectedIndex() == 0) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("23")));
            }
            if (cbbThoiHan.getSelectedIndex() == 1) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("24")));
            }
            if (cbbThoiHan.getSelectedIndex() == 2) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("25")));
            }
            if (cbbThoiHan.getSelectedIndex() == 3) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("12")));
            }
            if (cbbThoiHan.getSelectedIndex() == 4) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("17")));
            }
            if (cbbThoiHan.getSelectedIndex() == 5) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("18")));
            }
            if (cbbThoiHan.getSelectedIndex() == 6) {
                txtTien.setText(String.valueOf(quyDinhController.layGiaTien("19")));
            }
        }
    }//GEN-LAST:event_cbbThoiHanItemStateChanged

    private void cbbThoiHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThoiHanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbThoiHanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbb;
    private javax.swing.JComboBox<String> cbbKhu;
    private javax.swing.JComboBox<String> cbbThoiHan;
    private javax.swing.JComboBox<String> cbbViTri;
    private javax.swing.JLabel dsfgs;
    private javax.swing.JLabel gsdfff;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sdf;
    private javax.swing.JLabel sdfgg;
    private javax.swing.JLabel sdfsdf;
    private javax.swing.JLabel ss;
    private javax.swing.JLabel ssdfg;
    private javax.swing.JLabel sss;
    private javax.swing.JTextField txtBienSoXe;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtMaThe;
    private javax.swing.JTextField txtNgayDangKy;
    private javax.swing.JTextField txtNgayHetHan;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTien;
    // End of variables declaration//GEN-END:variables
}
