/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.baoCaoThongKeController;
import controller.dangKyTheThangController;
import controller.quyDinhController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.taiKhoan;
import model.thongKeTheThang;

/**
 *
 * @author Admin
 */
public class dangKyTheThang extends javax.swing.JPanel {

    private Date date;
    public taiKhoan tk;
    String ngayThangNam;

    /**
     * Creates new form dangKyTheThang
     */
    public dangKyTheThang(taiKhoan tk) {
        initComponents();
        this.tk = tk;
        date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        ngayThangNam = formatter.format(date);
        txtNgayDangKy.setText(ngayThangNam);
        txtTenNhanVien.setText(tk.getTenDangNhap());
        txtTien.setText(String.valueOf(quyDinhController.layGiaTien("11")));
        txtThucThu.setText(String.valueOf(quyDinhController.layGiaTien("11")));
        cbb.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sss = new javax.swing.JLabel();
        ss = new javax.swing.JLabel();
        sdf = new javax.swing.JLabel();
        sdfsdf = new javax.swing.JLabel();
        ssdfg = new javax.swing.JLabel();
        dsfgs = new javax.swing.JLabel();
        sdfgg = new javax.swing.JLabel();
        gsdfff = new javax.swing.JLabel();
        txtMaThe = new javax.swing.JTextField();
        txtBienSoXe = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtNgayDangKy = new javax.swing.JTextField();
        txtTien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtThucThu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Đăng ký thẻ tháng");

        sss.setText("Mã thẻ");

        ss.setText("Loại xe");

        sdf.setText("Biển số xe");

        sdfsdf.setText("Tên khách hàng");

        ssdfg.setText("CCCD");

        dsfgs.setText("Số điện thoại");

        sdfgg.setText("Ngày đăng ký");

        gsdfff.setText("Giá tiền");

        txtMaThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTheActionPerformed(evt);
            }
        });

        txtSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiActionPerformed(evt);
            }
        });

        txtTien.setEditable(false);
        txtTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienActionPerformed(evt);
            }
        });

        cbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O to", "Xe may", "Xe đap" }));
        cbb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbItemStateChanged(evt);
            }
        });
        cbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbActionPerformed(evt);
            }
        });

        jLabel3.setText("Nhân viên lập");

        txtTenNhanVien.setEditable(false);

        jLabel4.setText("Thực thu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ss)
                            .addComponent(sdf)
                            .addComponent(sss))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaThe)
                            .addComponent(cbb, 0, 100, Short.MAX_VALUE)
                            .addComponent(txtBienSoXe))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssdfg)
                            .addComponent(dsfgs)
                            .addComponent(sdfsdf))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtCCCD)
                            .addComponent(txtSoDienThoai))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(gsdfff))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTien, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtTenNhanVien)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sdfgg)
                                .addGap(18, 18, 18)
                                .addComponent(txtNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtThucThu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sss)
                    .addComponent(sdfsdf)
                    .addComponent(txtMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdfgg)
                    .addComponent(txtNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtThucThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ss)
                    .addComponent(gsdfff)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssdfg))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdf)
                    .addComponent(dsfgs)
                    .addComponent(txtBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 364, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTheActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtMaThe.getText().equals("") || txtBienSoXe.getText().equals("") || txtTenKhachHang.getText().equals("") || txtCCCD.getText().equals("") || txtSoDienThoai.getText().equals("") || txtTien.getText().equals("")) {
            JOptionPane.showMessageDialog(jButton1, "Hãy nhập đầy đủ thông tin");
        } else {
            String maLoaiThe = "6";
            if (cbb.getSelectedIndex() == 0) {
                maLoaiThe = "6";
            }
            if (cbb.getSelectedIndex() == 1) {
                maLoaiThe = "5";
            }
            if (cbb.getSelectedIndex() == 2){
                maLoaiThe = "4";
            }
            if (dangKyTheThangController.taoTheThang(txtMaThe.getText(),maLoaiThe, txtBienSoXe.getText(), txtTenKhachHang.getText(), txtCCCD.getText(), txtSoDienThoai.getText(), txtNgayDangKy.getText(), Integer.valueOf(txtTien.getText()), txtTenNhanVien.getText())) {
                thongKeTheThang tktt = new thongKeTheThang();
                tktt.setMaThe(txtMaThe.getText());
                tktt.setNgayDangKy(txtNgayDangKy.getText());
                tktt.setNgayDongTien(txtNgayDangKy.getText());
                tktt.setTien(Integer.valueOf(txtThucThu.getText()));
                tktt.setLoaiXe(cbb.getSelectedItem().toString());
                baoCaoThongKeController.taoLuotThongKeTheThang(tktt);
                JOptionPane.showMessageDialog(jButton1, "Tạo thẻ tháng mới thành công");
                txtMaThe.setText("");
                txtBienSoXe.setText("");
                txtTenKhachHang.setText("");
                txtCCCD.setText("");
                txtSoDienThoai.setText("");
            } else {
                JOptionPane.showMessageDialog(jButton1, "Mã thẻ đã tồn tại");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbItemStateChanged
        // TODO add your handling code here:
        String maQuyDinh = null;
        if (cbb.getSelectedIndex() == 0) {
            maQuyDinh = "11";
        }
        if (cbb.getSelectedIndex() == 1) {
            maQuyDinh = "10";
        }
        if (cbb.getSelectedIndex() == 2) {
            maQuyDinh = "9";
        }
        txtTien.setText(String.valueOf(quyDinhController.layGiaTien(maQuyDinh)));
        txtThucThu.setText(String.valueOf(quyDinhController.layGiaTien(maQuyDinh)));
    }//GEN-LAST:event_cbbItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtMaThe.setText("");
        txtBienSoXe.setText("");
        txtTenKhachHang.setText("");
        txtCCCD.setText("");
        txtSoDienThoai.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiActionPerformed

    private void cbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbActionPerformed

    private void txtTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbb;
    private javax.swing.JLabel dsfgs;
    private javax.swing.JLabel gsdfff;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sdf;
    private javax.swing.JLabel sdfgg;
    private javax.swing.JLabel sdfsdf;
    private javax.swing.JLabel ss;
    private javax.swing.JLabel ssdfg;
    private javax.swing.JLabel sss;
    private javax.swing.JTextField txtBienSoXe;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtMaThe;
    private javax.swing.JTextField txtNgayDangKy;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtThucThu;
    private javax.swing.JTextField txtTien;
    // End of variables declaration//GEN-END:variables
}
