/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.khuController;
import controller.nhanTraXeController;
import controller.quyDinhController;
import controller.taiKhoanController;
import controller.theController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.nhanTraXe;
import model.taiKhoan;

/**
 *
 * @author Admin
 */
public class hoaDonTraXe extends javax.swing.JFrame {

    private static nhanTraXe ntx;
    private static taiKhoan tk;

    /**
     * Creates new form hoaDonTraXe
     */
    public hoaDonTraXe(nhanTraXe ntx, taiKhoan tk) {
        initComponents();
        this.tk = tk;
        long tongTien = 0;
        this.ntx = ntx;
        clockThread clThread = new clockThread(txtGioTra);
        clThread.start();
        txtMaThe.setText(ntx.getMaThe());
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
        Date now = new Date();
        String date = sdf.format(now);
        txtNgayTra.setText(date);
        if (ntx.getLoaiThe().equals("The ngay")) {
            txtLoaiThe.setText("Thẻ ngày");
            txtMaKhu.setText(ntx.getMaKhu());
            txtMaViTri.setText(ntx.getMaViTri());
            txtNgayNhan.setText(ntx.getNgayNhan());
            txtGioNhan.setText(ntx.getGioNhan());
            txtBienSoXe.setText(ntx.getBienSoXe());
            txtMaThe.setText(ntx.getMaThe());
            txtBienSoXe.setText(ntx.getBienSoXe());
            txtLoaiXe.setText(ntx.getLoaiXe());
            Date ngayGioNhan = nhanTraXeController.formmat(txtNgayNhan.getText(), txtGioNhan.getText());
            Date ngayGioTra = nhanTraXeController.formmat(txtNgayTra.getText(), txtGioTra.getText());
            if (txtLoaiXe.getText().equals("Xe may")) {
                txtTongTien.setText(String.valueOf(nhanTraXeController.tinhTien(ngayGioNhan, ngayGioTra, "4", "5")));
            }
            if (txtLoaiXe.getText().equals("Xe dap")) {
                txtTongTien.setText(String.valueOf(nhanTraXeController.tinhTien(ngayGioNhan, ngayGioTra, "1", "2")));
            }
            if (txtLoaiXe.getText().equals("O to")) {
                txtTongTien.setText(String.valueOf(nhanTraXeController.tinhTienOto(ngayGioNhan, ngayGioTra, "7", "8")));
            }
        }
        if (ntx.getLoaiThe().equals("The thang")) {
            txtLoaiThe.setText("Thẻ tháng");
            txtMaKhu.setText(ntx.getMaKhu());
            txtMaViTri.setText(ntx.getMaViTri());
            txtNgayNhan.setText(ntx.getNgayNhan());
            txtGioNhan.setText(ntx.getGioNhan());
            txtTongTien.setText("0");
            txtLoaiXe.setText(ntx.getLoaiXe());
            txtBienSoXe.setText(ntx.getBienSoXe());
        }
        if (ntx.getLoaiThe().equals("The VIP")) {
            txtLoaiThe.setText("Thẻ VIP");
            txtMaKhu.setText(ntx.getMaKhu());
            txtMaViTri.setText(ntx.getMaViTri());
            txtNgayNhan.setText(ntx.getNgayNhan());
            txtGioNhan.setText(ntx.getGioNhan());
            txtTongTien.setText("0");
            txtLoaiXe.setText(ntx.getLoaiXe());
            txtBienSoXe.setText(ntx.getBienSoXe());
        }
    }

    class clockThread extends Thread {

        private JTextField txt;

        public clockThread(JTextField txt) {
            this.txt = txt;
        }

        public void run() {
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss ");
            while (true) {
                Date now = new Date();
                String st = sdf.format(now);
                txt.setText(st);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {

                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtGioTra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaThe = new javax.swing.JTextField();
        txtMaKhu = new javax.swing.JTextField();
        txtBienSoXe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgayTra = new javax.swing.JTextField();
        txtGioNhan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLoaiXe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNgayNhan = new javax.swing.JTextField();
        txtLoaiThe = new javax.swing.JTextField();
        txtMaViTri = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtGioTra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Mã vị trí");

        txtMaThe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTheActionPerformed(evt);
            }
        });

        txtMaKhu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtBienSoXe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Biển số xe");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ngày nhận");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã thẻ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Loại thẻ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Giờ trả");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Loại xe");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mã khu");

        txtNgayTra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtGioNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Ngày trả");

        txtLoaiXe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Giờ nhận");

        txtNgayNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtLoaiThe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMaViTri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaViTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaViTriActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Tổng tiền");

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addComponent(txtMaThe, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayNhan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLoaiThe)
                            .addComponent(txtBienSoXe)
                            .addComponent(txtGioTra, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGioNhan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgayTra, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaViTri, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaKhu, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLoaiXe, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTongTien))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoaiThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaKhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtGioNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtGioTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jButton1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTheActionPerformed

    private void txtMaViTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaViTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaViTriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (ntx.getLoaiThe().equals("The ngay")) {
            ntx.setNgayTra(txtNgayTra.getText());
            ntx.setGioTra(txtGioTra.getText());
            if (txtLoaiXe.getText().equals("Xe may")) {
                nhanTraXeController.traXeVeNgay(ntx, nhanTraXeController.tinhTien(nhanTraXeController.formmat(txtNgayNhan.getText(), txtGioNhan.getText()), nhanTraXeController.formmat(txtNgayTra.getText(), txtGioTra.getText()), "4", "5"));
                theController.traXeTheNgay(txtMaThe.getText());
                khuController.traXe(txtMaKhu.getText());
                taiKhoanController.traXe(tk, nhanTraXeController.tinhTien(nhanTraXeController.formmat(txtNgayNhan.getText(), txtGioNhan.getText()), nhanTraXeController.formmat(txtNgayTra.getText(), txtGioTra.getText()), "4", "5"));
                JOptionPane.showMessageDialog(rootPane, "Trả xe thành công");
            }
            if (txtLoaiXe.getText().equals("Xe dap")) {
                nhanTraXeController.traXeVeNgay(ntx, nhanTraXeController.tinhTien(nhanTraXeController.formmat(txtNgayNhan.getText(), txtGioNhan.getText()), nhanTraXeController.formmat(txtNgayTra.getText(), txtGioTra.getText()), "1", "2"));
                theController.traXeTheNgay(txtMaThe.getText());
                khuController.traXe(txtMaKhu.getText());
                taiKhoanController.traXe(tk, nhanTraXeController.tinhTien(nhanTraXeController.formmat(txtNgayNhan.getText(), txtGioNhan.getText()), nhanTraXeController.formmat(txtNgayTra.getText(), txtGioTra.getText()), "1", "2"));

                JOptionPane.showMessageDialog(rootPane, "Trả xe thành công");
            }
            if (txtLoaiXe.getText().equals("O to")) {
                nhanTraXeController.traXeVeNgay(ntx, nhanTraXeController.tinhTienOto(nhanTraXeController.formmat(txtNgayNhan.getText(), txtGioNhan.getText()), nhanTraXeController.formmat(txtNgayTra.getText(), txtGioTra.getText()), "7", "8"));
                theController.traXeTheNgay(txtMaThe.getText());
                khuController.traXe(txtMaKhu.getText());
                taiKhoanController.traXe(tk, nhanTraXeController.tinhTien(nhanTraXeController.formmat(txtNgayNhan.getText(), txtGioNhan.getText()), nhanTraXeController.formmat(txtNgayTra.getText(), txtGioTra.getText()), "7", "8"));
                JOptionPane.showMessageDialog(rootPane, "Trả xe thành công");
            }
            dispose();
        }
        if (ntx.getLoaiThe().equals("The thang")) {
            ntx.setNgayTra(txtNgayTra.getText());
            ntx.setGioTra(txtGioTra.getText());
            if (nhanTraXeController.traXeVeThangVaVip(ntx)) {
                JOptionPane.showMessageDialog(rootPane, "Trả xe thành công");
            }
            taiKhoanController.traXe(tk, 0);
            theController.traXeTheThang(txtMaThe.getText());
            khuController.traXe(txtMaKhu.getText());
        }
        if (ntx.getLoaiThe().equals("The VIP")) {
            ntx.setNgayTra(txtNgayTra.getText());
            ntx.setGioTra(txtGioTra.getText());
            taiKhoanController.traXe(tk, 0);
            if (nhanTraXeController.traXeVeThangVaVip(ntx)) {
                JOptionPane.showMessageDialog(rootPane, "Trả xe thành công");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hoaDonTraXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hoaDonTraXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hoaDonTraXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hoaDonTraXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hoaDonTraXe(ntx, tk).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBienSoXe;
    private javax.swing.JTextField txtGioNhan;
    private javax.swing.JTextField txtGioTra;
    private javax.swing.JTextField txtLoaiThe;
    private javax.swing.JTextField txtLoaiXe;
    private javax.swing.JTextField txtMaKhu;
    private javax.swing.JTextField txtMaThe;
    private javax.swing.JTextField txtMaViTri;
    private javax.swing.JTextField txtNgayNhan;
    private javax.swing.JTextField txtNgayTra;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
