/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.khuController;
import controller.nhanTraXeController;
import controller.taiKhoanController;
import controller.theController;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.khu;
import model.nhanTraXe;
import model.taiKhoan;
import model.the;

/**
 *
 * @author Admin
 */
class clockThread extends Thread {

    private JTextField txt;

    public clockThread(JTextField txt) {
        this.txt = txt;
    }

    public void run() {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss ");
        while (true) {
            Date now = new Date();
            String st = sdf.format(now);
            txt.setText(st);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {

            }
        }
    }
}

public class nhanXe extends javax.swing.JPanel {

    private taiKhoan tk;
    StringBuilder sb = new StringBuilder();

    /**
     * Creates new form nhanXe
     */
    public nhanXe(taiKhoan tk) {
        initComponents();
        this.tk = tk;
        clockThread clk = new clockThread(txtGioNhan);
        clk.start();
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(now);
        txtNgayNhan.setText(date);
        ArrayList<khu> list = khuController.layDanhSachKhuThuong((String) cbbLoaiXe.getSelectedItem());
        for (int i = 0; i < list.size(); i++) {
            cbbKhuVuc.insertItemAt(list.get(i).getMaKhu(), i);
        }
        cbbKhuVuc.setSelectedItem(list.get(0).getMaKhu());
        txtViTri.setEnabled(false);
        cbbLoaiXe.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaThe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBienSoXe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbbKhuVuc = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtNgayNhan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGioNhan = new javax.swing.JTextField();
        cbbLoaiXe = new javax.swing.JComboBox<>();
        txtViTri = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbbLoaiThe = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Nhận xe");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã thẻ");

        txtMaThe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTheActionPerformed(evt);
            }
        });
        txtMaThe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaTheKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaTheKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Loại xe");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Biển số xe");

        txtBienSoXe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Khu vực");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Vị trí");

        cbbKhuVuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Ngày nhận");

        txtNgayNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Giờ nhận");

        txtGioNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbbLoaiXe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbLoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O to", "Xe may", "Xe dap" }));
        cbbLoaiXe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbLoaiXeItemStateChanged(evt);
            }
        });
        cbbLoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiXeActionPerformed(evt);
            }
        });

        txtViTri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaThe, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(txtViTri))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayNhan)
                            .addComponent(cbbLoaiXe, 0, 85, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(5, 5, 5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBienSoXe, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(txtGioNhan))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(cbbKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbbKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtNgayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtGioNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Loại thẻ");

        cbbLoaiThe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbbLoaiThe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thẻ ngày", "Thẻ tháng", "Thẻ vip" }));
        cbbLoaiThe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbLoaiTheItemStateChanged(evt);
            }
        });
        cbbLoaiThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiTheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(386, 386, 386))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cbbLoaiThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbLoaiThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 253, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void cbbLoaiTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiTheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLoaiTheActionPerformed

    private void cbbLoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLoaiXeActionPerformed

    private void cbbLoaiTheItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbLoaiTheItemStateChanged
        // TODO add your handling code here:
        if (cbbLoaiThe.getSelectedIndex() == 2) {
            txtViTri.setEnabled(true);
            cbbLoaiXe.removeItem("Xe dap");
            ArrayList<khu> list = khuController.layDanhSachKhuVip((String) cbbLoaiXe.getSelectedItem());
            cbbKhuVuc.removeAllItems();
            for (int i = 0; i < list.size(); i++) {
                cbbKhuVuc.insertItemAt(list.get(i).getMaKhu(), i);
            }
            cbbKhuVuc.setSelectedItem(list.get(0).getMaKhu());
        } else {
            if (cbbLoaiXe.getItemCount() <= 2) {
                cbbLoaiXe.addItem("Xe dap");
            }
            ArrayList<khu> list = khuController.layDanhSachKhuThuong((String) cbbLoaiXe.getSelectedItem());
            cbbKhuVuc.removeAllItems();
            for (int i = 0; i < list.size(); i++) {
                cbbKhuVuc.insertItemAt(list.get(i).getMaKhu(), i);
            }
            cbbKhuVuc.setSelectedItem(list.get(0).getMaKhu());
            txtViTri.setEnabled(false);
        }
    }//GEN-LAST:event_cbbLoaiTheItemStateChanged

    private void cbbLoaiXeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbLoaiXeItemStateChanged
        // TODO add your handling code here:
        if (cbbLoaiThe.getSelectedIndex() != 2) {
            ArrayList<khu> list = khuController.layDanhSachKhuThuong((String) cbbLoaiXe.getSelectedItem());
            cbbKhuVuc.removeAllItems();
            for (int i = 0; i < list.size(); i++) {
                cbbKhuVuc.insertItemAt(list.get(i).getMaKhu(), i);
            }
            cbbKhuVuc.setSelectedItem(list.get(0).getMaKhu());
        } else {
            ArrayList<khu> list = khuController.layDanhSachKhuVip((String) cbbLoaiXe.getSelectedItem());
            cbbKhuVuc.removeAllItems();
            for (int i = 0; i < list.size(); i++) {
                cbbKhuVuc.insertItemAt(list.get(i).getMaKhu(), i);
            }
            cbbKhuVuc.setSelectedItem(list.get(0).getMaKhu());
        }
    }//GEN-LAST:event_cbbLoaiXeItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (cbbLoaiThe.getSelectedIndex() == 0) {
            if (txtMaThe.getText().equals("")) {
                JOptionPane.showMessageDialog(jButton1, "Hãy nhập mã thẻ");
            } else {
                if (txtBienSoXe.getText().equals("")) {
                    JOptionPane.showMessageDialog(jButton1, "Hãy nhập biển số xe");
                } else {
                    if (theController.checkTonTai(txtMaThe.getText())) {
                        if (theController.checkCoXe(txtMaThe.getText()) == null) {
                            nhanTraXe ntx = new nhanTraXe();
                            ntx.setLoaiThe("The ngay");
                            String maLoaiThe = "3";
                            ntx.setMaThe(txtMaThe.getText());
                            ntx.setLoaiXe("O to");
                            if (cbbLoaiXe.getSelectedIndex() == 1) {
                                ntx.setLoaiXe("Xe may");
                                maLoaiThe = "2";
                            }
                            if (cbbLoaiXe.getSelectedIndex() == 2) {
                                ntx.setLoaiXe("Xe dap");
                                maLoaiThe = "1";
                            }
                            ntx.setBienSoXe(txtBienSoXe.getText());
                            ntx.setMaKhu((String) cbbKhuVuc.getSelectedItem());
                            ntx.setMaViTri("null");
                            ntx.setGioNhan(txtGioNhan.getText());
                            ntx.setNgayNhan(txtNgayNhan.getText());
                            ntx.setNgayTra("");
                            ntx.setGioTra("");
                            ntx.setLoai(0);
                            ntx.setPhiGui("");
                            nhanTraXeController.nhanXe(ntx);
                            khuController.nhanXe((String) cbbKhuVuc.getSelectedItem());
                            theController.nhanXeTheNgay(txtMaThe.getText(), txtBienSoXe.getText(), (String) cbbKhuVuc.getSelectedItem(), maLoaiThe);
                            JOptionPane.showMessageDialog(jButton1, "Nhận xe thành công");
                            taiKhoanController.nhanXe(tk);
                        } else {
                            JOptionPane.showMessageDialog(jButton1, "Thẻ đang được dùng để gửi xe khác");
                        }
                    } else {
                        JOptionPane.showMessageDialog(jButton1, "Thẻ không tồn tại trong hệ thống");
                    }
                }
            }
        }
        if (cbbLoaiThe.getSelectedIndex() == 1) {
            if (txtMaThe.getText().equals("")) {
                JOptionPane.showMessageDialog(jButton1, "Hãy nhập mã thẻ");
            } else {
                nhanTraXe ntx = new nhanTraXe();
                ntx.setLoaiThe("The thang");
                ntx.setMaThe(txtMaThe.getText());
                ntx.setLoaiXe("O to");
                if (cbbLoaiXe.getSelectedIndex() == 1) {
                    ntx.setLoaiXe("Xe may");
                }
                if (cbbLoaiXe.getSelectedIndex() == 2) {
                    ntx.setLoaiXe("Xe dap");
                }
                ntx.setBienSoXe(txtBienSoXe.getText());
                ntx.setMaKhu((String) cbbKhuVuc.getSelectedItem());
                ntx.setMaViTri("null");
                ntx.setGioNhan(txtGioNhan.getText());
                ntx.setNgayNhan(txtNgayNhan.getText());
                ntx.setNgayTra("");
                ntx.setGioTra("");
                ntx.setLoai(0);
                ntx.setPhiGui("");
                nhanTraXeController.nhanXe(ntx);
                khuController.nhanXe((String) cbbKhuVuc.getSelectedItem());
                theController.nhanXeTheThang(ntx.getMaKhu(), ntx.getMaThe());
                taiKhoanController.nhanXe(tk);
                JOptionPane.showMessageDialog(jButton1, "Nhận xe thành công");
            }
        }
        if (cbbLoaiThe.getSelectedIndex() == 2) {
            if (txtMaThe.getText().equals("")) {
                JOptionPane.showMessageDialog(jButton1, "Hãy nhập mã thẻ");
            } else {
                nhanTraXe ntx = new nhanTraXe();
                ntx.setLoaiThe("The VIP");
                ntx.setMaThe(txtMaThe.getText());
                ntx.setLoaiXe("O to");
                if (cbbLoaiXe.getSelectedIndex() == 1) {
                    ntx.setLoaiXe("Xe may");
                }

                ntx.setBienSoXe(txtBienSoXe.getText());
                ntx.setMaKhu((String) cbbKhuVuc.getSelectedItem());
                ntx.setMaViTri(txtViTri.getText());
                ntx.setGioNhan(txtGioNhan.getText());
                ntx.setNgayNhan(txtNgayNhan.getText());
                ntx.setNgayTra("");
                ntx.setGioTra("");
                ntx.setLoai(0);
                ntx.setPhiGui("");
                nhanTraXeController.nhanXe(ntx);
                theController.nhanXeTheVip(ntx.getMaKhu(), ntx.getMaViTri(), ntx.getMaThe());
                JOptionPane.showMessageDialog(jButton1, "Nhận xe thành công");
                taiKhoanController.nhanXe(tk);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtMaTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTheActionPerformed

    private void txtMaTheKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaTheKeyTyped
        // TODO add your handling code here:
        if (cbbLoaiThe.getSelectedIndex() == 1) {
            if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) {
                sb.deleteCharAt(sb.length() - 1);
            } else {
                sb.append(evt.getKeyChar());
            }
            the t = theController.layThongTinTheThang(sb.toString());
            if (t != null) {
                txtBienSoXe.setText(t.getBienSoXe());
                if (t.getMaLoaiThe().equals("4")) {
                    cbbLoaiXe.setSelectedIndex(2);
                }
                if (t.getMaLoaiThe().equals("5")) {
                    cbbLoaiXe.setSelectedIndex(1);
                }
                if (t.getMaLoaiThe().equals("6")) {
                    cbbLoaiXe.setSelectedIndex(0);
                }
            } else {
                txtBienSoXe.setText("");
            }
        }
        if (cbbLoaiThe.getSelectedIndex() == 2) {
            if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) {
                sb.deleteCharAt(sb.length() - 1);
            } else {
                sb.append(evt.getKeyChar());
            }
            the t = theController.layThongTinTheVip(sb.toString());
            if (t != null) {
                txtBienSoXe.setText(t.getBienSoXe());
                txtViTri.setText(t.getMaViTri());
                if (t.getMaLoaiThe().equals("8")) {
                    cbbLoaiXe.setSelectedIndex(0);
                }
                if (t.getMaLoaiThe().equals("7")) {
                    cbbLoaiXe.setSelectedIndex(1);
                }
            } else {
                txtBienSoXe.setText("");
            }
        }
    }//GEN-LAST:event_txtMaTheKeyTyped

    private void txtMaTheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaTheKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTheKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbKhuVuc;
    private javax.swing.JComboBox<String> cbbLoaiThe;
    private javax.swing.JComboBox<String> cbbLoaiXe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtBienSoXe;
    private javax.swing.JTextField txtGioNhan;
    private javax.swing.JTextField txtMaThe;
    private javax.swing.JTextField txtNgayNhan;
    private javax.swing.JTextField txtViTri;
    // End of variables declaration//GEN-END:variables
}
